<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>mlas</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>Preview</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="System.Data" />
    <Reference Include="FastColoredTextBox">
      <HintPath>..\bin\FastColoredTextBox.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\bin\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.Web" />
    <Reference Include="Excel">
      <HintPath>..\bin\Excel.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="10.0.11" />
  </ItemGroup>
</Project>